#include <stdio.h>
#include <string.h>
#include <stdlib.h>

/*

      C89 _ C99 _ UNX  _ XOPN
                \ IEEE _ BSD
                       \ SVID

  __C89  Include header of C89 and C89_OPT
  __C99  Include header of C89 and C89_OPT
  __UNX  Include header of P_UNIX_98 and P_UNIX_OPT
  ___IEEE               of P_IEEE *
  ___XOPN               of P_XSI
  __BSD, __SVID         of P_POSIX and P_POSIX_OPT
*/


#define UX_FUNC           (1 << 1)
#define UX_C89            (1 << 2)
#define UX_C89_E          (1 << 3)
#define UX_C99            (1 << 4)
#define UX_C99_T          (1 << 5)


struct axHeaderTable {
  const char*   _name;
  int           _flags;
}

axHeaderTable [] = {

    { "FD_CLR"  , UX_FUNC },
    { "FD_ISSET"  , UX_FUNC },
    { "FD_SET"  , UX_FUNC },
    { "FD_ZERO" , UX_FUNC },
    { "_Exit" , UX_FUNC | UX_C99 },
    { "_exit" , UX_FUNC },
    { "_longjmp"  , UX_FUNC },
    { "_setjmp" , UX_FUNC },
    { "_tolower"  , UX_FUNC },
    { "_toupper"  , UX_FUNC },
    { "a64l"  , UX_FUNC },
    { "abort" , UX_FUNC | UX_C89 | UX_C99 },
    { "abs" , UX_FUNC | UX_C89 | UX_C99 },
    { "accept"  , UX_FUNC },
    { "access"  , UX_FUNC },
    { "acos"  , UX_FUNC | UX_C89 | UX_C99 },
    { "acosf" , UX_FUNC | UX_C99 },
    { "acosh" , UX_FUNC | UX_C99 },
    { "acoshf"  , UX_FUNC | UX_C99 },
    { "acoshl"  , UX_FUNC | UX_C99 },
    { "acosl" , UX_FUNC | UX_C99 },
    { "aio_cancel"  , UX_FUNC },
    { "aio_error" , UX_FUNC },
    { "aio_fsync" , UX_FUNC },
    { "aio_read"  , UX_FUNC },
    { "aio_return"  , UX_FUNC },
    { "aio_suspend" , UX_FUNC },
    { "aio_write" , UX_FUNC },
    { "alarm" , UX_FUNC },
    { "asctime" , UX_FUNC | UX_C89 | UX_C99 },
    { "asctime_r" , UX_FUNC },
    { "asin"  , UX_FUNC | UX_C89 | UX_C99 },
    { "asinf" , UX_FUNC | UX_C99 },
    { "asinh" , UX_FUNC | UX_C99 },
    { "asinhf"  , UX_FUNC | UX_C99 },
    { "asinhl"  , UX_FUNC | UX_C99 },
    { "asinl" , UX_FUNC | UX_C99 },
    { "assert"  , UX_FUNC | UX_C89 | UX_C99 },
    { "atan"  , UX_FUNC | UX_C89 | UX_C99 },
    { "atan2" , UX_FUNC | UX_C89 | UX_C99 },
    { "atan2f"  , UX_FUNC | UX_C99 },
    { "atan2l"  , UX_FUNC | UX_C99 },
    { "atanf" , UX_FUNC | UX_C99 },
    { "atanh" , UX_FUNC | UX_C99 },
    { "atanhf"  , UX_FUNC | UX_C99 },
    { "atanhl"  , UX_FUNC | UX_C99 },
    { "atanl" , UX_FUNC | UX_C99 },
    { "atexit"  , UX_FUNC | UX_C89 | UX_C99 },
    { "atof"  , UX_FUNC | UX_C89 | UX_C99 },
    { "atoi"  , UX_FUNC | UX_C89 | UX_C99 },
    { "atol"  , UX_FUNC | UX_C89 | UX_C99 },
    { "atoll" , UX_FUNC | UX_C99 },
    { "basename"  , UX_FUNC },
    { "bcmp"  , UX_FUNC },
    { "bcopy" , UX_FUNC },
    { "bind"  , UX_FUNC },
    { "bsd_signal"  , UX_FUNC },
    { "bsearch" , UX_FUNC | UX_C89 | UX_C99 },
    { "btowc" , UX_FUNC | UX_C99 },
    { "bzero" , UX_FUNC },
    { "cabs"  , UX_FUNC | UX_C99 },
    { "cabsf" , UX_FUNC | UX_C99 },
    { "cabsl" , UX_FUNC | UX_C99 },
    { "cacos" , UX_FUNC | UX_C99 },
    { "cacosf"  , UX_FUNC | UX_C99 },
    { "cacosh"  , UX_FUNC | UX_C99 },
    { "cacoshf" , UX_FUNC | UX_C99 },
    { "cacoshl" , UX_FUNC | UX_C99 },
    { "cacosl"  , UX_FUNC | UX_C99 },
    { "calloc"  , UX_FUNC | UX_C89 | UX_C99 },
    { "carg"  , UX_FUNC | UX_C99 },
    { "cargf" , UX_FUNC | UX_C99 },
    { "cargl" , UX_FUNC | UX_C99 },
    { "casin" , UX_FUNC | UX_C99 },
    { "casinf"  , UX_FUNC | UX_C99 },
    { "casinh"  , UX_FUNC | UX_C99 },
    { "casinhf" , UX_FUNC | UX_C99 },
    { "casinhl" , UX_FUNC | UX_C99 },
    { "casinl"  , UX_FUNC | UX_C99 },
    { "catan" , UX_FUNC | UX_C99 },
    { "catanf"  , UX_FUNC | UX_C99 },
    { "catanh"  , UX_FUNC | UX_C99 },
    { "catanhf" , UX_FUNC | UX_C99 },
    { "catanhl" , UX_FUNC | UX_C99 },
    { "catanl"  , UX_FUNC | UX_C99 },
    { "catclose"  , UX_FUNC },
    { "catgets" , UX_FUNC },
    { "catopen" , UX_FUNC },
    { "cbrt"  , UX_FUNC | UX_C99 },
    { "cbrtf" , UX_FUNC | UX_C99 },
    { "cbrtl" , UX_FUNC | UX_C99 },
    { "ccos"  , UX_FUNC | UX_C99 },
    { "ccosf" , UX_FUNC | UX_C99 },
    { "ccosh" , UX_FUNC | UX_C99 },
    { "ccoshf"  , UX_FUNC | UX_C99 },
    { "ccoshl"  , UX_FUNC | UX_C99 },
    { "ccosl" , UX_FUNC | UX_C99 },
    { "ceil"  , UX_FUNC | UX_C89 | UX_C99 },
    { "ceilf" , UX_FUNC | UX_C99 },
    { "ceill" , UX_FUNC | UX_C99 },
    { "cexp"  , UX_FUNC | UX_C99 },
    { "cexpf" , UX_FUNC | UX_C99 },
    { "cexpl" , UX_FUNC | UX_C99 },
    { "cfgetispeed" , UX_FUNC },
    { "cfgetospeed" , UX_FUNC },
    { "cfsetispeed" , UX_FUNC },
    { "cfsetospeed" , UX_FUNC },
    { "chdir" , UX_FUNC },
    { "chmod" , UX_FUNC },
    { "chown" , UX_FUNC },
    { "cimag" , UX_FUNC | UX_C99 },
    { "cimagf"  , UX_FUNC | UX_C99 },
    { "cimagl"  , UX_FUNC | UX_C99 },
    { "clearerr"  , UX_FUNC | UX_C89 | UX_C99 },
    { "clock" , UX_FUNC | UX_C89 | UX_C99 },
    { "clock_getcpuclockid" , UX_FUNC },
    { "clock_getres"  , UX_FUNC },
    { "clock_gettime" , UX_FUNC },
    { "clock_nanosleep" , UX_FUNC },
    { "clock_settime" , UX_FUNC },
    { "clog"  , UX_FUNC | UX_C99 },
    { "clogf" , UX_FUNC | UX_C99 },
    { "clogl" , UX_FUNC | UX_C99 },
    { "close" , UX_FUNC },
    { "closedir"  , UX_FUNC },
    { "closelog"  , UX_FUNC },
    { "confstr" , UX_FUNC },
    { "conj"  , UX_FUNC | UX_C99 },
    { "conjf" , UX_FUNC | UX_C99 },
    { "conjl" , UX_FUNC | UX_C99 },
    { "connect" , UX_FUNC },
    { "copysign"  , UX_FUNC | UX_C99 },
    { "copysignf" , UX_FUNC | UX_C99 },
    { "copysignl" , UX_FUNC | UX_C99 },
    { "cos" , UX_FUNC | UX_C89 | UX_C99 },
    { "cosf"  , UX_FUNC | UX_C99 },
    { "cosh"  , UX_FUNC | UX_C89 | UX_C99 },
    { "coshf" , UX_FUNC | UX_C99 },
    { "coshl" , UX_FUNC | UX_C99 },
    { "cosl"  , UX_FUNC | UX_C99 },
    { "cpow"  , UX_FUNC | UX_C99 },
    { "cpowf" , UX_FUNC | UX_C99 },
    { "cpowl" , UX_FUNC | UX_C99 },
    { "cproj" , UX_FUNC | UX_C99 },
    { "cprojf"  , UX_FUNC | UX_C99 },
    { "cprojl"  , UX_FUNC | UX_C99 },
    { "creal" , UX_FUNC | UX_C99 },
    { "crealf"  , UX_FUNC | UX_C99 },
    { "creall"  , UX_FUNC | UX_C99 },
    { "creat" , UX_FUNC },
    { "crypt" , UX_FUNC },
    { "csin"  , UX_FUNC | UX_C99 },
    { "csinf" , UX_FUNC | UX_C99 },
    { "csinh" , UX_FUNC | UX_C99 },
    { "csinhf"  , UX_FUNC | UX_C99 },
    { "csinhl"  , UX_FUNC | UX_C99 },
    { "csinl" , UX_FUNC | UX_C99 },
    { "csqrt" , UX_FUNC | UX_C99 },
    { "csqrtf"  , UX_FUNC | UX_C99 },
    { "csqrtl"  , UX_FUNC | UX_C99 },
    { "ctan"  , UX_FUNC | UX_C99 },
    { "ctanf" , UX_FUNC | UX_C99 },
    { "ctanh" , UX_FUNC | UX_C99 },
    { "ctanhf"  , UX_FUNC | UX_C99 },
    { "ctanhl"  , UX_FUNC | UX_C99 },
    { "ctanl" , UX_FUNC | UX_C99 },
    { "ctermid" , UX_FUNC },
    { "ctime" , UX_FUNC | UX_C89 | UX_C99 },
    { "ctime_r" , UX_FUNC },
    { "daylight"  , 0 },
    { "dbm_clearerr"  , UX_FUNC },
    { "dbm_close" , UX_FUNC },
    { "dbm_delete"  , UX_FUNC },
    { "dbm_error" , UX_FUNC },
    { "dbm_fetch" , UX_FUNC },
    { "dbm_firstkey"  , UX_FUNC },
    { "dbm_nextkey" , UX_FUNC },
    { "dbm_open"  , UX_FUNC },
    { "dbm_store" , UX_FUNC },
    { "difftime"  , UX_FUNC | UX_C89 | UX_C99 },
    { "dirname" , UX_FUNC },
    { "div" , UX_FUNC | UX_C89 | UX_C99 },
    { "dlclose" , UX_FUNC },
    { "dlerror" , UX_FUNC },
    { "dlopen"  , UX_FUNC },
    { "dlsym" , UX_FUNC },
    { "drand48" , UX_FUNC },
    { "dup" , UX_FUNC },
    { "dup2"  , UX_FUNC },
    { "ecvt"  , UX_FUNC },
    { "encrypt" , UX_FUNC },
    { "endgrent"  , UX_FUNC },
    { "endhostent"  , UX_FUNC },
    { "endnetent" , UX_FUNC },
    { "endprotoent" , UX_FUNC },
    { "endpwent"  , UX_FUNC },
    { "endservent"  , UX_FUNC },
    { "endutxent" , UX_FUNC },
    { "environ" , 0 },
    { "erand48" , UX_FUNC },
    { "erf" , UX_FUNC | UX_C99 },
    { "erfc"  , UX_FUNC | UX_C99 },
    { "erfcf" , UX_FUNC | UX_C99 },
    { "erfcl" , UX_FUNC | UX_C99 },
    { "erff"  , UX_FUNC | UX_C99 },
    { "erfl"  , UX_FUNC | UX_C99 },
    { "errno" ,   UX_C89 | UX_C99 },
    { "execl" , UX_FUNC },
    { "execle"  , UX_FUNC },
    { "execlp"  , UX_FUNC },
    { "execv" , UX_FUNC },
    { "execve"  , UX_FUNC },
    { "execvp"  , UX_FUNC },
    { "exit"  , UX_FUNC | UX_C89 | UX_C99 },
    { "exp" , UX_FUNC | UX_C89 | UX_C99 },
    { "exp2"  , UX_FUNC | UX_C99 },
    { "exp2f" , UX_FUNC | UX_C99 },
    { "exp2l" , UX_FUNC | UX_C99 },
    { "expf"  , UX_FUNC | UX_C99 },
    { "expl"  , UX_FUNC | UX_C99 },
    { "expm1" , UX_FUNC | UX_C99 },
    { "expm1f"  , UX_FUNC | UX_C99 },
    { "expm1l"  , UX_FUNC | UX_C99 },
    { "fabs"  , UX_FUNC | UX_C89 | UX_C99 },
    { "fabsf" , UX_FUNC | UX_C99 },
    { "fabsl" , UX_FUNC | UX_C99 },
    { "fattach" , UX_FUNC },
    { "fchdir"  , UX_FUNC },
    { "fchmod"  , UX_FUNC },
    { "fchown"  , UX_FUNC },
    { "fclose"  , UX_FUNC | UX_C89 | UX_C99 },
    { "fcntl" , UX_FUNC },
    { "fcvt"  , UX_FUNC },
    { "fdatasync" , UX_FUNC },
    { "fdetach" , UX_FUNC },
    { "fdim"  , UX_FUNC | UX_C99 },
    { "fdimf" , UX_FUNC | UX_C99 },
    { "fdiml" , UX_FUNC | UX_C99 },
    { "fdopen"  , UX_FUNC },
    { "feclearexcept" , UX_FUNC | UX_C99 },
    { "fegetenv"  , UX_FUNC | UX_C99 },
    { "fegetexceptflag" , UX_FUNC | UX_C99 },
    { "fegetround"  , UX_FUNC | UX_C99 },
    { "feholdexcept"  , UX_FUNC | UX_C99 },
    { "feof"  , UX_FUNC | UX_C89 | UX_C99 },
    { "feraiseexcept" , UX_FUNC | UX_C99 },
    { "ferror"  , UX_FUNC | UX_C89 | UX_C99 },
    { "fesetenv"  , UX_FUNC | UX_C99 },
    { "fesetexceptflag" , UX_FUNC | UX_C99 },
    { "fesetround"  , UX_FUNC | UX_C99 },
    { "fetestexcept"  , UX_FUNC | UX_C99 },
    { "feupdateenv" , UX_FUNC | UX_C99 },
    { "fflush"  , UX_FUNC | UX_C89 | UX_C99 },
    { "ffs" , UX_FUNC },
    { "fgetc" , UX_FUNC | UX_C89 | UX_C99 },
    { "fgetpos" , UX_FUNC | UX_C89 | UX_C99 },
    { "fgets" , UX_FUNC | UX_C89 | UX_C99 },
    { "fgetwc"  , UX_FUNC | UX_C99 },
    { "fgetws"  , UX_FUNC | UX_C99 },
    { "fileno"  , UX_FUNC },
    { "flockfile" , UX_FUNC },
    { "floor" , UX_FUNC | UX_C89 | UX_C99 },
    { "floorf"  , UX_FUNC | UX_C99 },
    { "floorl"  , UX_FUNC | UX_C99 },
    { "fma" , UX_FUNC | UX_C99 },
    { "fmaf"  , UX_FUNC | UX_C99 },
    { "fmal"  , UX_FUNC | UX_C99 },
    { "fmax"  , UX_FUNC | UX_C99 },
    { "fmaxf" , UX_FUNC | UX_C99 },
    { "fmaxl" , UX_FUNC | UX_C99 },
    { "fmin"  , UX_FUNC | UX_C99 },
    { "fminf" , UX_FUNC | UX_C99 },
    { "fminl" , UX_FUNC | UX_C99 },
    { "fmod"  , UX_FUNC | UX_C89 | UX_C99 },
    { "fmodf" , UX_FUNC | UX_C99 },
    { "fmodl" , UX_FUNC | UX_C99 },
    { "fmtmsg"  , UX_FUNC },
    { "fnmatch" , UX_FUNC },
    { "fopen" , UX_FUNC | UX_C89 | UX_C99 },
    { "fork"  , UX_FUNC },
    { "fpathconf" , UX_FUNC },
    { "fpclassify"  , UX_FUNC | UX_C99 },
    { "fprintf" , UX_FUNC | UX_C89 | UX_C99 },
    { "fputc" , UX_FUNC | UX_C89 | UX_C99 },
    { "fputs" , UX_FUNC | UX_C89 | UX_C99 },
    { "fputwc"  , UX_FUNC | UX_C99 },
    { "fputws"  , UX_FUNC | UX_C99 },
    { "fread" , UX_FUNC | UX_C89 | UX_C99 },
    { "free"  , UX_FUNC | UX_C89 | UX_C99 },
    { "freeaddrinfo"  , UX_FUNC },
    { "freopen" , UX_FUNC | UX_C89 | UX_C99 },
    { "frexp" , UX_FUNC | UX_C89 | UX_C99 },
    { "frexpf"  , UX_FUNC | UX_C99 },
    { "frexpl"  , UX_FUNC | UX_C99 },
    { "fscanf"  , UX_FUNC | UX_C89 | UX_C99 },
    { "fseek" , UX_FUNC | UX_C89 | UX_C99 },
    { "fseeko"  , UX_FUNC },
    { "fsetpos" , UX_FUNC | UX_C89 | UX_C99 },
    { "fstat" , UX_FUNC },
    { "fstatvfs"  , UX_FUNC },
    { "fsync" , UX_FUNC },
    { "ftell" , UX_FUNC | UX_C89 | UX_C99 },
    { "ftello"  , UX_FUNC },
    { "ftime" , UX_FUNC },
    { "ftok"  , UX_FUNC },
    { "ftruncate" , UX_FUNC },
    { "ftrylockfile"  , UX_FUNC },
    { "ftw" , UX_FUNC },
    { "funlockfile" , UX_FUNC },
    { "fwide" , UX_FUNC | UX_C99 },
    { "fwprintf"  , UX_FUNC | UX_C99 },
    { "fwrite"  , UX_FUNC | UX_C89 | UX_C99 },
    { "fwscanf" , UX_FUNC | UX_C99 },
    { "gai_strerror"  , UX_FUNC },
    { "gcvt"  , UX_FUNC },
    { "getaddrinfo" , UX_FUNC },
    { "getc"  , UX_FUNC | UX_C89 | UX_C99 },
    { "getc_unlocked" , UX_FUNC },
    { "getchar" , UX_FUNC | UX_C89 | UX_C99 },
    { "getchar_unlocked"  , UX_FUNC },
    { "getcontext"  , UX_FUNC },
    { "getcwd"  , UX_FUNC },
    { "getdate" , UX_FUNC },
    { "getdate_err" , 0 },
    { "getegid" , UX_FUNC },
    { "getenv"  , UX_FUNC | UX_C89 | UX_C99 },
    { "geteuid" , UX_FUNC },
    { "getgid"  , UX_FUNC },
    { "getgrent"  , UX_FUNC },
    { "getgrgid"  , UX_FUNC },
    { "getgrgid_r"  , UX_FUNC },
    { "getgrnam"  , UX_FUNC },
    { "getgrnam_r"  , UX_FUNC },
    { "getgroups" , UX_FUNC },
    { "gethostbyaddr" , UX_FUNC },
    { "gethostbyname" , UX_FUNC },
    { "gethostent"  , UX_FUNC },
    { "gethostid" , UX_FUNC },
    { "gethostname" , UX_FUNC },
    { "getitimer" , UX_FUNC },
    { "getlogin"  , UX_FUNC },
    { "getlogin_r"  , UX_FUNC },
    { "getmsg"  , UX_FUNC },
    { "getnameinfo" , UX_FUNC },
    { "getnetbyaddr"  , UX_FUNC },
    { "getnetbyname"  , UX_FUNC },
    { "getnetent" , UX_FUNC },
    { "getopt"  , UX_FUNC },
    { "getpeername" , UX_FUNC },
    { "getpgid" , UX_FUNC },
    { "getpgrp" , UX_FUNC },
    { "getpid"  , UX_FUNC },
    { "getpmsg" , UX_FUNC },
    { "getppid" , UX_FUNC },
    { "getpriority" , UX_FUNC },
    { "getprotobyname"  , UX_FUNC },
    { "getprotobynumber"  , UX_FUNC },
    { "getprotoent" , UX_FUNC },
    { "getpwent"  , UX_FUNC },
    { "getpwnam"  , UX_FUNC },
    { "getpwnam_r"  , UX_FUNC },
    { "getpwuid"  , UX_FUNC },
    { "getpwuid_r"  , UX_FUNC },
    { "getrlimit" , UX_FUNC },
    { "getrusage" , UX_FUNC },
    { "gets"  , UX_FUNC | UX_C89 | UX_C99 },
    { "getservbyname" , UX_FUNC },
    { "getservbyport" , UX_FUNC },
    { "getservent"  , UX_FUNC },
    { "getsid"  , UX_FUNC },
    { "getsockname" , UX_FUNC },
    { "getsockopt"  , UX_FUNC },
    { "getsubopt" , UX_FUNC },
    { "gettimeofday"  , UX_FUNC },
    { "getuid"  , UX_FUNC },
    { "getutxent" , UX_FUNC },
    { "getutxid"  , UX_FUNC },
    { "getutxline"  , UX_FUNC },
    { "getwc" , UX_FUNC | UX_C99 },
    { "getwchar"  , UX_FUNC | UX_C99 },
    { "getwd" , UX_FUNC },
    { "glob"  , UX_FUNC },
    { "globfree"  , UX_FUNC },
    { "gmtime"  , UX_FUNC | UX_C89 | UX_C99 },
    { "gmtime_r"  , UX_FUNC },
    { "grantpt" , UX_FUNC },
    { "h_errno" , 0 },
    { "hcreate" , UX_FUNC },
    { "hdestroy"  , UX_FUNC },
    { "hsearch" , UX_FUNC },
    { "htonl" , UX_FUNC },
    { "htons" , UX_FUNC },
    { "hypot" , UX_FUNC | UX_C99 },
    { "hypotf"  , UX_FUNC | UX_C99 },
    { "hypotl"  , UX_FUNC | UX_C99 },
    { "iconv" , UX_FUNC },
    { "iconv_close" , UX_FUNC },
    { "iconv_open"  , UX_FUNC },
    { "if_freenameindex"  , UX_FUNC },
    { "if_indextoname"  , UX_FUNC },
    { "if_nameindex"  , UX_FUNC },
    { "if_nametoindex"  , UX_FUNC },
    { "ilogb" , UX_FUNC | UX_C99 },
    { "ilogbf"  , UX_FUNC | UX_C99 },
    { "ilogbl"  , UX_FUNC | UX_C99 },
    { "imaxabs" , UX_FUNC | UX_C99 },
    { "imaxdiv" , UX_FUNC | UX_C99 },
    { "index" , UX_FUNC },
    { "inet_addr" , UX_FUNC },
    { "inet_ntoa" , UX_FUNC },
    { "inet_ntop" , UX_FUNC },
    { "inet_pton" , UX_FUNC },
    { "initstate" , UX_FUNC },
    { "insque"  , UX_FUNC },
    { "ioctl" , UX_FUNC },
    { "isalnum" , UX_FUNC | UX_C89 | UX_C99 },
    { "isalpha" , UX_FUNC | UX_C89 | UX_C99 },
    { "isascii" , UX_FUNC },
    { "isastream" , UX_FUNC },
    { "isatty"  , UX_FUNC },
    { "isblank" , UX_FUNC | UX_C99 },
    { "iscntrl" , UX_FUNC | UX_C89 | UX_C99 },
    { "isdigit" , UX_FUNC | UX_C89 | UX_C99 },
    { "isfinite"  , UX_FUNC | UX_C99 },
    { "isgraph" , UX_FUNC | UX_C89 | UX_C99 },
    { "isgreater" , UX_FUNC | UX_C99 },
    { "isgreaterequal"  , UX_FUNC | UX_C99 },
    { "isinf" , UX_FUNC | UX_C99 },
    { "isless"  , UX_FUNC | UX_C99 },
    { "islessequal" , UX_FUNC | UX_C99 },
    { "islessgreater" , UX_FUNC | UX_C99 },
    { "islower" , UX_FUNC | UX_C89 | UX_C99 },
    { "isnan" , UX_FUNC },
    { "isnormal"  , UX_FUNC | UX_C99 },
    { "isprint" , UX_FUNC | UX_C89 | UX_C99 },
    { "ispunct" , UX_FUNC | UX_C89 | UX_C99 },
    { "isspace" , UX_FUNC | UX_C89 | UX_C99 },
    { "isunordered" , UX_FUNC | UX_C99 },
    { "isupper" , UX_FUNC | UX_C89 | UX_C99 },
    { "iswalnum"  , UX_FUNC | UX_C99 },
    { "iswalpha"  , UX_FUNC | UX_C99 },
    { "iswblank"  , UX_FUNC | UX_C99 },
    { "iswcntrl"  , UX_FUNC | UX_C99 },
    { "iswctype"  , UX_FUNC | UX_C99 },
    { "iswdigit"  , UX_FUNC | UX_C99 },
    { "iswgraph"  , UX_FUNC | UX_C99 },
    { "iswlower"  , UX_FUNC | UX_C99 },
    { "iswprint"  , UX_FUNC | UX_C99 },
    { "iswpunct"  , UX_FUNC | UX_C99 },
    { "iswspace"  , UX_FUNC | UX_C99 },
    { "iswupper"  , UX_FUNC | UX_C99 },
    { "iswxdigit" , UX_FUNC | UX_C99 },
    { "isxdigit"  , UX_FUNC | UX_C89 | UX_C99 },
    { "j0"  , UX_FUNC },
    { "j1"  , UX_FUNC },
    { "jn"  , UX_FUNC },
    { "jrand48" , UX_FUNC },
    { "kill"  , UX_FUNC },
    { "killpg"  , UX_FUNC },
    { "l64a"  , UX_FUNC },
    { "labs"  , UX_FUNC | UX_C89 | UX_C99 },
    { "lchown"  , UX_FUNC },
    { "lcong48" , UX_FUNC },
    { "ldexp" , UX_FUNC | UX_C89 | UX_C99 },
    { "ldexpf"  , UX_FUNC | UX_C99 },
    { "ldexpl"  , UX_FUNC | UX_C99 },
    { "ldiv"  , UX_FUNC | UX_C89 | UX_C99 },
    { "lfind" , UX_FUNC },
    { "lgamma"  , UX_FUNC | UX_C99 },
    { "lgammaf" , UX_FUNC | UX_C99 },
    { "lgammal" , UX_FUNC | UX_C99 },
    { "link"  , UX_FUNC },
    { "lio_listio"  , UX_FUNC },
    { "listen"  , UX_FUNC },
    { "llabs" , UX_FUNC | UX_C99 },
    { "lldiv" , UX_FUNC | UX_C99 },
    { "llrint"  , UX_FUNC | UX_C99 },
    { "llrintf" , UX_FUNC | UX_C99 },
    { "llrintl" , UX_FUNC | UX_C99 },
    { "llround" , UX_FUNC | UX_C99 },
    { "llroundf"  , UX_FUNC | UX_C99 },
    { "llroundl"  , UX_FUNC | UX_C99 },
    { "localeconv"  , UX_FUNC | UX_C89 | UX_C99 },
    { "localtime" , UX_FUNC | UX_C89 | UX_C99 },
    { "localtime_r" , UX_FUNC },
    { "lockf" , UX_FUNC },
    { "log" , UX_FUNC | UX_C89 | UX_C99 },
    { "log10" , UX_FUNC | UX_C89 | UX_C99 },
    { "log10f"  , UX_FUNC | UX_C99 },
    { "log10l"  , UX_FUNC | UX_C99 },
    { "log1p" , UX_FUNC | UX_C99 },
    { "log1pf"  , UX_FUNC | UX_C99 },
    { "log1pl"  , UX_FUNC | UX_C99 },
    { "log2"  , UX_FUNC | UX_C99 },
    { "log2f" , UX_FUNC | UX_C99 },
    { "log2l" , UX_FUNC | UX_C99 },
    { "logb"  , UX_FUNC | UX_C99 },
    { "logbf" , UX_FUNC | UX_C99 },
    { "logbl" , UX_FUNC | UX_C99 },
    { "logf"  , UX_FUNC | UX_C99 },
    { "logl"  , UX_FUNC | UX_C99 },
    { "longjmp" , UX_FUNC | UX_C89 | UX_C99 },
    { "lrand48" , UX_FUNC },
    { "lrint" , UX_FUNC | UX_C99 },
    { "lrintf"  , UX_FUNC | UX_C99 },
    { "lrintl"  , UX_FUNC | UX_C99 },
    { "lround"  , UX_FUNC | UX_C99 },
    { "lroundf" , UX_FUNC | UX_C99 },
    { "lroundl" , UX_FUNC | UX_C99 },
    { "lsearch" , UX_FUNC },
    { "lseek" , UX_FUNC },
    { "lstat" , UX_FUNC },
    { "makecontext" , UX_FUNC },
    { "malloc"  , UX_FUNC | UX_C89 | UX_C99 },
    { "mblen" , UX_FUNC | UX_C89 | UX_C99 },
    { "mbrlen"  , UX_FUNC | UX_C99 },
    { "mbrtowc" , UX_FUNC | UX_C99 },
    { "mbsinit" , UX_FUNC | UX_C99 },
    { "mbsrtowcs" , UX_FUNC | UX_C99 },
    { "mbstowcs"  , UX_FUNC | UX_C89 | UX_C99 },
    { "mbtowc"  , UX_FUNC | UX_C89 | UX_C99 },
    { "memccpy" , UX_FUNC },
    { "memchr"  , UX_FUNC | UX_C89 | UX_C99 },
    { "memcmp"  , UX_FUNC | UX_C89 | UX_C99 },
    { "memcpy"  , UX_FUNC | UX_C89 | UX_C99 },
    { "memmove" , UX_FUNC | UX_C89 | UX_C99 },
    { "memset"  , UX_FUNC | UX_C89 | UX_C99 },
    { "mkdir" , UX_FUNC },
    { "mkfifo"  , UX_FUNC },
    { "mknod" , UX_FUNC },
    { "mkstemp" , UX_FUNC },
    { "mktemp"  , UX_FUNC },
    { "mktime"  , UX_FUNC | UX_C89 | UX_C99 },
    { "mlock" , UX_FUNC },
    { "mlockall"  , UX_FUNC },
    { "mmap"  , UX_FUNC },
    { "modf"  , UX_FUNC | UX_C89 | UX_C99 },
    { "modff" , UX_FUNC | UX_C99 },
    { "modfl" , UX_FUNC | UX_C99 },
    { "mprotect"  , UX_FUNC },
    { "mq_close"  , UX_FUNC },
    { "mq_getattr"  , UX_FUNC },
    { "mq_notify" , UX_FUNC },
    { "mq_open" , UX_FUNC },
    { "mq_receive"  , UX_FUNC },
    { "mq_send" , UX_FUNC },
    { "mq_setattr"  , UX_FUNC },
    { "mq_timedreceive" , UX_FUNC },
    { "mq_timedsend"  , UX_FUNC },
    { "mq_unlink" , UX_FUNC },
    { "mrand48" , UX_FUNC },
    { "msgctl"  , UX_FUNC },
    { "msgget"  , UX_FUNC },
    { "msgrcv"  , UX_FUNC },
    { "msgsnd"  , UX_FUNC },
    { "msync" , UX_FUNC },
    { "munlock" , UX_FUNC },
    { "munlockall"  , UX_FUNC },
    { "munmap"  , UX_FUNC },
    { "nan" , UX_FUNC | UX_C99 },
    { "nanf"  , UX_FUNC | UX_C99 },
    { "nanl"  , UX_FUNC | UX_C99 },
    { "nanosleep" , UX_FUNC },
    { "nearbyint" , UX_FUNC | UX_C99 },
    { "nearbyintf"  , UX_FUNC | UX_C99 },
    { "nearbyintl"  , UX_FUNC | UX_C99 },
    { "nextafter" , UX_FUNC | UX_C99 },
    { "nextafterf"  , UX_FUNC | UX_C99 },
    { "nextafterl"  , UX_FUNC | UX_C99 },
    { "nexttoward"  , UX_FUNC | UX_C99 },
    { "nexttowardf" , UX_FUNC | UX_C99 },
    { "nexttowardl" , UX_FUNC | UX_C99 },
    { "nftw"  , UX_FUNC },
    { "nice"  , UX_FUNC },
    { "nl_langinfo" , UX_FUNC },
    { "nrand48" , UX_FUNC },
    { "ntohl" , UX_FUNC },
    { "ntohs" , UX_FUNC },
    { "open"  , UX_FUNC },
    { "opendir" , UX_FUNC },
    { "openlog" , UX_FUNC },
    { "optarg"  , 0 },
    { "opterr"  , 0 },
    { "optind"  , 0 },
    { "optopt"  , 0 },
    { "pathconf"  , UX_FUNC },
    { "pause" , UX_FUNC },
    { "pclose"  , UX_FUNC },
    { "perror"  , UX_FUNC | UX_C89 | UX_C99 },
    { "pipe"  , UX_FUNC },
    { "poll"  , UX_FUNC },
    { "popen" , UX_FUNC },
    { "posix_fadvise" , UX_FUNC },
    { "posix_fallocate" , UX_FUNC },
    { "posix_madvise" , UX_FUNC },
    { "posix_mem_offset"  , UX_FUNC },
    { "posix_memalign"  , UX_FUNC },
    { "posix_openpt"  , UX_FUNC },
    { "posix_spawn" , UX_FUNC },
    { "posix_spawn_file_actions_addclose" , UX_FUNC },
    { "posix_spawn_file_actions_adddup2"  , UX_FUNC },
    { "posix_spawn_file_actions_addopen"  , UX_FUNC },
    { "posix_spawn_file_actions_destroy"  , UX_FUNC },
    { "posix_spawn_file_actions_init" , UX_FUNC },
    { "posix_spawnattr_destroy" , UX_FUNC },
    { "posix_spawnattr_getflags"  , UX_FUNC },
    { "posix_spawnattr_getpgroup" , UX_FUNC },
    { "posix_spawnattr_getschedparam" , UX_FUNC },
    { "posix_spawnattr_getschedpolicy"  , UX_FUNC },
    { "posix_spawnattr_getsigdefault" , UX_FUNC },
    { "posix_spawnattr_getsigmask"  , UX_FUNC },
    { "posix_spawnattr_init"  , UX_FUNC },
    { "posix_spawnattr_setflags"  , UX_FUNC },
    { "posix_spawnattr_setpgroup" , UX_FUNC },
    { "posix_spawnattr_setschedparam" , UX_FUNC },
    { "posix_spawnattr_setschedpolicy"  , UX_FUNC },
    { "posix_spawnattr_setsigdefault" , UX_FUNC },
    { "posix_spawnattr_setsigmask"  , UX_FUNC },
    { "posix_spawnp"  , UX_FUNC },
    { "posix_trace_attr_destroy"  , UX_FUNC },
    { "posix_trace_attr_getclockres"  , UX_FUNC },
    { "posix_trace_attr_getcreatetime"  , UX_FUNC },
    { "posix_trace_attr_getgenversion"  , UX_FUNC },
    { "posix_trace_attr_getinherited" , UX_FUNC },
    { "posix_trace_attr_getlogfullpolicy" , UX_FUNC },
    { "posix_trace_attr_getlogsize" , UX_FUNC },
    { "posix_trace_attr_getmaxdatasize" , UX_FUNC },
    { "posix_trace_attr_getmaxsystemeventsize"  , UX_FUNC },
    { "posix_trace_attr_getmaxusereventsize"  , UX_FUNC },
    { "posix_trace_attr_getname"  , UX_FUNC },
    { "posix_trace_attr_getstreamfullpolicy"  , UX_FUNC },
    { "posix_trace_attr_getstreamsize"  , UX_FUNC },
    { "posix_trace_attr_init" , UX_FUNC },
    { "posix_trace_attr_setinherited" , UX_FUNC },
    { "posix_trace_attr_setlogfullpolicy" , UX_FUNC },
    { "posix_trace_attr_setlogsize" , UX_FUNC },
    { "posix_trace_attr_setmaxdatasize" , UX_FUNC },
    { "posix_trace_attr_setname"  , UX_FUNC },
    { "posix_trace_attr_setstreamfullpolicy"  , UX_FUNC },
    { "posix_trace_attr_setstreamsize"  , UX_FUNC },
    { "posix_trace_clear" , UX_FUNC },
    { "posix_trace_close" , UX_FUNC },
    { "posix_trace_create"  , UX_FUNC },
    { "posix_trace_create_withlog"  , UX_FUNC },
    { "posix_trace_event" , UX_FUNC },
    { "posix_trace_eventid_equal" , UX_FUNC },
    { "posix_trace_eventid_get_name"  , UX_FUNC },
    { "posix_trace_eventid_open"  , UX_FUNC },
    { "posix_trace_eventset_add"  , UX_FUNC },
    { "posix_trace_eventset_del"  , UX_FUNC },
    { "posix_trace_eventset_empty"  , UX_FUNC },
    { "posix_trace_eventset_fill" , UX_FUNC },
    { "posix_trace_eventset_ismember" , UX_FUNC },
    { "posix_trace_eventtypelist_getnext_id"  , UX_FUNC },
    { "posix_trace_eventtypelist_rewind"  , UX_FUNC },
    { "posix_trace_flush" , UX_FUNC },
    { "posix_trace_get_attr"  , UX_FUNC },
    { "posix_trace_get_filter"  , UX_FUNC },
    { "posix_trace_get_status"  , UX_FUNC },
    { "posix_trace_getnext_event" , UX_FUNC },
    { "posix_trace_open"  , UX_FUNC },
    { "posix_trace_rewind"  , UX_FUNC },
    { "posix_trace_set_filter"  , UX_FUNC },
    { "posix_trace_shutdown"  , UX_FUNC },
    { "posix_trace_start" , UX_FUNC },
    { "posix_trace_stop"  , UX_FUNC },
    { "posix_trace_timedgetnext_event"  , UX_FUNC },
    { "posix_trace_trid_eventid_open" , UX_FUNC },
    { "posix_trace_trygetnext_event"  , UX_FUNC },
    { "posix_typed_mem_get_info"  , UX_FUNC },
    { "posix_typed_mem_open"  , UX_FUNC },
    { "pow" , UX_FUNC | UX_C89 | UX_C99 },
    { "powf"  , UX_FUNC | UX_C99 },
    { "powl"  , UX_FUNC | UX_C99 },
    { "pread" , UX_FUNC },
    { "printf"  , UX_FUNC | UX_C89 | UX_C99 },
    { "pselect" , UX_FUNC },
    { "pthread_atfork"  , UX_FUNC },
    { "pthread_attr_destroy"  , UX_FUNC },
    { "pthread_attr_getdetachstate" , UX_FUNC },
    { "pthread_attr_getguardsize" , UX_FUNC },
    { "pthread_attr_getinheritsched"  , UX_FUNC | UX_C99_T },
    { "pthread_attr_getschedparam"  , UX_FUNC },
    { "pthread_attr_getschedpolicy" , UX_FUNC | UX_C99_T },
    { "pthread_attr_getscope" , UX_FUNC | UX_C99_T },
    { "pthread_attr_getstack" , UX_FUNC },
    { "pthread_attr_getstackaddr" , UX_FUNC | UX_C99_T },
    { "pthread_attr_getstacksize" , UX_FUNC | UX_C99_T },
    { "pthread_attr_init" , UX_FUNC },
    { "pthread_attr_setdetachstate" , UX_FUNC },
    { "pthread_attr_setguardsize" , UX_FUNC },
    { "pthread_attr_setinheritsched"  , UX_FUNC | UX_C99_T },
    { "pthread_attr_setschedparam"  , UX_FUNC },
    { "pthread_attr_setschedpolicy" , UX_FUNC | UX_C99_T },
    { "pthread_attr_setscope" , UX_FUNC | UX_C99_T },
    { "pthread_attr_setstack" , UX_FUNC },
    { "pthread_attr_setstackaddr" , UX_FUNC | UX_C99_T },
    { "pthread_attr_setstacksize" , UX_FUNC | UX_C99_T },
    { "pthread_barrier_destroy" , UX_FUNC },
    { "pthread_barrier_init"  , UX_FUNC },
    { "pthread_barrier_wait"  , UX_FUNC },
    { "pthread_barrierattr_destroy" , UX_FUNC },
    { "pthread_barrierattr_getpshared"  , UX_FUNC },
    { "pthread_barrierattr_init"  , UX_FUNC },
    { "pthread_barrierattr_setpshared"  , UX_FUNC },
    { "pthread_cancel"  , UX_FUNC },
    { "pthread_cleanup_pop" , UX_FUNC },
    { "pthread_cleanup_push"  , UX_FUNC },
    { "pthread_cond_broadcast"  , UX_FUNC },
    { "pthread_cond_destroy"  , UX_FUNC },
    { "pthread_cond_init" , UX_FUNC },
    { "pthread_cond_signal" , UX_FUNC },
    { "pthread_cond_timedwait"  , UX_FUNC },
    { "pthread_cond_wait" , UX_FUNC },
    { "pthread_condattr_destroy"  , UX_FUNC },
    { "pthread_condattr_getclock" , UX_FUNC },
    { "pthread_condattr_getpshared" , UX_FUNC | UX_C99_T },
    { "pthread_condattr_init" , UX_FUNC },
    { "pthread_condattr_setclock" , UX_FUNC },
    { "pthread_condattr_setpshared" , UX_FUNC | UX_C99_T },
    { "pthread_create"  , UX_FUNC },
    { "pthread_detach"  , UX_FUNC },
    { "pthread_equal" , UX_FUNC },
    { "pthread_exit"  , UX_FUNC },
    { "pthread_getconcurrency"  , UX_FUNC },
    { "pthread_getcpuclockid" , UX_FUNC },
    { "pthread_getschedparam" , UX_FUNC | UX_C99_T },
    { "pthread_getspecific" , UX_FUNC },
    { "pthread_join"  , UX_FUNC },
    { "pthread_key_create"  , UX_FUNC },
    { "pthread_key_delete"  , UX_FUNC },
    { "pthread_kill"  , UX_FUNC },
    { "pthread_mutex_destroy" , UX_FUNC },
    { "pthread_mutex_getprioceiling"  , UX_FUNC | UX_C99_T },
    { "pthread_mutex_init"  , UX_FUNC },
    { "pthread_mutex_lock"  , UX_FUNC },
    { "pthread_mutex_setprioceiling"  , UX_FUNC | UX_C99_T },
    { "pthread_mutex_timedlock" , UX_FUNC },
    { "pthread_mutex_trylock" , UX_FUNC },
    { "pthread_mutex_unlock"  , UX_FUNC },
    { "pthread_mutexattr_destroy" , UX_FUNC },
    { "pthread_mutexattr_getprioceiling"  , UX_FUNC | UX_C99_T },
    { "pthread_mutexattr_getprotocol" , UX_FUNC | UX_C99_T },
    { "pthread_mutexattr_getpshared"  , UX_FUNC | UX_C99_T },
    { "pthread_mutexattr_gettype" , UX_FUNC },
    { "pthread_mutexattr_init"  , UX_FUNC },
    { "pthread_mutexattr_setprioceiling"  , UX_FUNC | UX_C99_T },
    { "pthread_mutexattr_setprotocol" , UX_FUNC | UX_C99_T },
    { "pthread_mutexattr_setpshared"  , UX_FUNC | UX_C99_T },
    { "pthread_mutexattr_settype" , UX_FUNC },
    { "pthread_once"  , UX_FUNC },
    { "pthread_rwlock_destroy"  , UX_FUNC },
    { "pthread_rwlock_init" , UX_FUNC },
    { "pthread_rwlock_rdlock" , UX_FUNC },
    { "pthread_rwlock_timedrdlock"  , UX_FUNC },
    { "pthread_rwlock_timedwrlock"  , UX_FUNC },
    { "pthread_rwlock_tryrdlock"  , UX_FUNC },
    { "pthread_rwlock_trywrlock"  , UX_FUNC },
    { "pthread_rwlock_unlock" , UX_FUNC },
    { "pthread_rwlock_wrlock" , UX_FUNC },
    { "pthread_rwlockattr_destroy"  , UX_FUNC },
    { "pthread_rwlockattr_getpshared" , UX_FUNC },
    { "pthread_rwlockattr_init" , UX_FUNC },
    { "pthread_rwlockattr_setpshared" , UX_FUNC },
    { "pthread_self"  , UX_FUNC },
    { "pthread_setcancelstate"  , UX_FUNC },
    { "pthread_setcanceltype" , UX_FUNC },
    { "pthread_setconcurrency"  , UX_FUNC },
    { "pthread_setschedparam" , UX_FUNC | UX_C99_T },
    { "pthread_setschedprio"  , UX_FUNC },
    { "pthread_setspecific" , UX_FUNC },
    { "pthread_sigmask" , UX_FUNC },
    { "pthread_spin_destroy"  , UX_FUNC },
    { "pthread_spin_init" , UX_FUNC },
    { "pthread_spin_lock" , UX_FUNC },
    { "pthread_spin_trylock"  , UX_FUNC },
    { "pthread_spin_unlock" , UX_FUNC },
    { "pthread_testcancel"  , UX_FUNC },
    { "ptsname" , UX_FUNC },
    { "putc"  , UX_FUNC | UX_C89 | UX_C99 },
    { "putc_unlocked" , UX_FUNC },
    { "putchar" , UX_FUNC | UX_C89 | UX_C99 },
    { "putchar_unlocked"  , UX_FUNC },
    { "putenv"  , UX_FUNC },
    { "putmsg"  , UX_FUNC },
    { "putpmsg" , UX_FUNC },
    { "puts"  , UX_FUNC | UX_C89 | UX_C99 },
    { "pututxline"  , UX_FUNC },
    { "putwc" , UX_FUNC | UX_C99 },
    { "putwchar"  , UX_FUNC | UX_C99 },
    { "pwrite"  , UX_FUNC },
    { "qsort" , UX_FUNC | UX_C89 | UX_C99 },
    { "raise" , UX_FUNC | UX_C89 | UX_C99 },
    { "rand"  , UX_FUNC | UX_C89 | UX_C99 },
    { "rand_r"  , UX_FUNC },
    { "random"  , UX_FUNC },
    { "read"  , UX_FUNC },
    { "readdir" , UX_FUNC },
    { "readdir_r" , UX_FUNC },
    { "readlink"  , UX_FUNC },
    { "readv" , UX_FUNC },
    { "realloc" , UX_FUNC | UX_C89 | UX_C99 },
    { "realpath"  , UX_FUNC },
    { "recv"  , UX_FUNC },
    { "recvfrom"  , UX_FUNC },
    { "recvmsg" , UX_FUNC },
    { "regcomp" , UX_FUNC },
    { "regerror"  , UX_FUNC },
    { "regexec" , UX_FUNC },
    { "regfree" , UX_FUNC },
    { "remainder" , UX_FUNC | UX_C99 },
    { "remainderf"  , UX_FUNC | UX_C99 },
    { "remainderl"  , UX_FUNC | UX_C99 },
    { "remove"  , UX_FUNC | UX_C89 | UX_C99 },
    { "remque"  , UX_FUNC },
    { "remquo"  , UX_FUNC | UX_C99 },
    { "remquof" , UX_FUNC | UX_C99 },
    { "remquol" , UX_FUNC | UX_C99 },
    { "rename"  , UX_FUNC | UX_C89 | UX_C99 },
    { "rewind"  , UX_FUNC | UX_C89 | UX_C99 },
    { "rewinddir" , UX_FUNC },
    { "rindex"  , UX_FUNC },
    { "rint"  , UX_FUNC | UX_C99 },
    { "rintf" , UX_FUNC | UX_C99 },
    { "rintl" , UX_FUNC | UX_C99 },
    { "rmdir" , UX_FUNC },
    { "round" , UX_FUNC | UX_C99 },
    { "roundf"  , UX_FUNC | UX_C99 },
    { "roundl"  , UX_FUNC | UX_C99 },
    { "scalb" , UX_FUNC },
    { "scalbln" , UX_FUNC | UX_C99 },
    { "scalblnf"  , UX_FUNC | UX_C99 },
    { "scalblnl"  , UX_FUNC | UX_C99 },
    { "scalbn"  , UX_FUNC | UX_C99 },
    { "scalbnf" , UX_FUNC | UX_C99 },
    { "scalbnl" , UX_FUNC | UX_C99 },
    { "scanf" , UX_FUNC | UX_C89 | UX_C99 },
    { "sched_get_priority_max"  , UX_FUNC },
    { "sched_get_priority_min"  , UX_FUNC },
    { "sched_getparam"  , UX_FUNC },
    { "sched_getscheduler"  , UX_FUNC },
    { "sched_rr_get_interval" , UX_FUNC },
    { "sched_setparam"  , UX_FUNC },
    { "sched_setscheduler"  , UX_FUNC },
    { "sched_yield" , UX_FUNC },
    { "seed48"  , UX_FUNC },
    { "seekdir" , UX_FUNC },
    { "select"  , UX_FUNC },
    { "sem_close" , UX_FUNC },
    { "sem_destroy" , UX_FUNC },
    { "sem_getvalue"  , UX_FUNC },
    { "sem_init"  , UX_FUNC },
    { "sem_open"  , UX_FUNC },
    { "sem_post"  , UX_FUNC },
    { "sem_timedwait" , UX_FUNC },
    { "sem_trywait" , UX_FUNC },
    { "sem_unlink"  , UX_FUNC },
    { "sem_wait"  , UX_FUNC },
    { "semctl"  , UX_FUNC },
    { "semget"  , UX_FUNC },
    { "semop" , UX_FUNC },
    { "send"  , UX_FUNC },
    { "sendmsg" , UX_FUNC },
    { "sendto"  , UX_FUNC },
    { "setbuf"  , UX_FUNC | UX_C89 | UX_C99 },
    { "setcontext"  , UX_FUNC },
    { "setegid" , UX_FUNC },
    { "setenv"  , UX_FUNC },
    { "seteuid" , UX_FUNC },
    { "setgid"  , UX_FUNC },
    { "setgrent"  , UX_FUNC },
    { "sethostent"  , UX_FUNC },
    { "setitimer" , UX_FUNC },
    { "setjmp"  , UX_FUNC | UX_C89 | UX_C99 },
    { "setkey"  , UX_FUNC },
    { "setlocale" , UX_FUNC | UX_C89 | UX_C99 },
    { "setlogmask"  , UX_FUNC },
    { "setnetent" , UX_FUNC },
    { "setpgid" , UX_FUNC },
    { "setpgrp" , UX_FUNC },
    { "setpriority" , UX_FUNC },
    { "setprotoent" , UX_FUNC },
    { "setpwent"  , UX_FUNC },
    { "setregid"  , UX_FUNC },
    { "setreuid"  , UX_FUNC },
    { "setrlimit" , UX_FUNC },
    { "setservent"  , UX_FUNC },
    { "setsid"  , UX_FUNC },
    { "setsockopt"  , UX_FUNC },
    { "setstate"  , UX_FUNC },
    { "setuid"  , UX_FUNC },
    { "setutxent" , UX_FUNC },
    { "setvbuf" , UX_FUNC | UX_C89 | UX_C99 },
    { "shm_open"  , UX_FUNC },
    { "shm_unlink"  , UX_FUNC },
    { "shmat" , UX_FUNC },
    { "shmctl"  , UX_FUNC },
    { "shmdt" , UX_FUNC },
    { "shmget"  , UX_FUNC },
    { "shutdown"  , UX_FUNC },
    { "sigaction" , UX_FUNC },
    { "sigaddset" , UX_FUNC },
    { "sigaltstack" , UX_FUNC },
    { "sigdelset" , UX_FUNC },
    { "sigemptyset" , UX_FUNC },
    { "sigfillset"  , UX_FUNC },
    { "sighold" , UX_FUNC },
    { "sigignore" , UX_FUNC },
    { "siginterrupt"  , UX_FUNC },
    { "sigismember" , UX_FUNC },
    { "siglongjmp"  , UX_FUNC },
    { "signal"  , UX_FUNC | UX_C89 | UX_C99 },
    { "signbit" , UX_FUNC | UX_C99 },
    { "signgam" , 0 },
    { "sigpause"  , UX_FUNC },
    { "sigpending"  , UX_FUNC },
    { "sigprocmask" , UX_FUNC },
    { "sigqueue"  , UX_FUNC },
    { "sigrelse"  , UX_FUNC },
    { "sigset"  , UX_FUNC },
    { "sigsetjmp" , UX_FUNC },
    { "sigsuspend"  , UX_FUNC },
    { "sigtimedwait"  , UX_FUNC },
    { "sigwait" , UX_FUNC },
    { "sigwaitinfo" , UX_FUNC },
    { "sin" , UX_FUNC | UX_C89 | UX_C99 },
    { "sinf"  , UX_FUNC | UX_C99 },
    { "sinh"  , UX_FUNC | UX_C89 | UX_C99 },
    { "sinhf" , UX_FUNC | UX_C99 },
    { "sinhl" , UX_FUNC | UX_C99 },
    { "sinl"  , UX_FUNC | UX_C99 },
    { "sleep" , UX_FUNC },
    { "snprintf"  , UX_FUNC | UX_C99 },
    { "sockatmark"  , UX_FUNC },
    { "socket"  , UX_FUNC },
    { "socketpair"  , UX_FUNC },
    { "sprintf" , UX_FUNC | UX_C89 | UX_C99 },
    { "sqrt"  , UX_FUNC | UX_C89 | UX_C99 },
    { "sqrtf" , UX_FUNC | UX_C99 },
    { "sqrtl" , UX_FUNC | UX_C99 },
    { "srand" , UX_FUNC | UX_C89 | UX_C99 },
    { "srand48" , UX_FUNC },
    { "srandom" , UX_FUNC },
    { "sscanf"  , UX_FUNC | UX_C89 | UX_C99 },
    { "stat"  , UX_FUNC },
    { "statvfs" , UX_FUNC },
    { "stderr"  ,   UX_C89 | UX_C99 },
    { "stdin" ,   UX_C89 | UX_C99 },
    { "stdout"  ,   UX_C89 | UX_C99 },
    { "strcasecmp"  , UX_FUNC },
    { "strcat"  , UX_FUNC | UX_C89 | UX_C99 },
    { "strchr"  , UX_FUNC | UX_C89 | UX_C99 },
    { "strcmp"  , UX_FUNC | UX_C89 | UX_C99 },
    { "strcoll" , UX_FUNC | UX_C89 | UX_C99 },
    { "strcpy"  , UX_FUNC | UX_C89 | UX_C99 },
    { "strcspn" , UX_FUNC | UX_C89 | UX_C99 },
    { "strdup"  , UX_FUNC },
    { "strerror"  , UX_FUNC | UX_C89 | UX_C99 },
    { "strerror_r"  , UX_FUNC },
    { "strfmon" , UX_FUNC },
    { "strftime"  , UX_FUNC | UX_C89 | UX_C99 },
    { "strlen"  , UX_FUNC | UX_C89 | UX_C99 },
    { "strncasecmp" , UX_FUNC },
    { "strncat" , UX_FUNC | UX_C89 | UX_C99 },
    { "strncmp" , UX_FUNC | UX_C89 | UX_C99 },
    { "strncpy" , UX_FUNC | UX_C89 | UX_C99 },
    { "strpbrk" , UX_FUNC | UX_C89 | UX_C99 },
    { "strptime"  , UX_FUNC },
    { "strrchr" , UX_FUNC | UX_C89 | UX_C99 },
    { "strspn"  , UX_FUNC | UX_C89 | UX_C99 },
    { "strstr"  , UX_FUNC | UX_C89 | UX_C99 },
    { "strtod"  , UX_FUNC | UX_C89 | UX_C99 },
    { "strtof"  , UX_FUNC | UX_C99 },
    { "strtoimax" , UX_FUNC | UX_C99 },
    { "strtok"  , UX_FUNC | UX_C89 | UX_C99 },
    { "strtok_r"  , UX_FUNC },
    { "strtol"  , UX_FUNC | UX_C89 | UX_C99 },
    { "strtold" , UX_FUNC | UX_C99 },
    { "strtoll" , UX_FUNC | UX_C99 },
    { "strtoul" , UX_FUNC | UX_C89 | UX_C99 },
    { "strtoull"  , UX_FUNC | UX_C99 },
    { "strtoumax" , UX_FUNC | UX_C99 },
    { "strxfrm" , UX_FUNC | UX_C89 | UX_C99 },
    { "swab"  , UX_FUNC },
    { "swapcontext" , UX_FUNC },
    { "swprintf"  , UX_FUNC | UX_C99 },
    { "swscanf" , UX_FUNC | UX_C99 },
    { "symlink" , UX_FUNC },
    { "sync"  , UX_FUNC },
    { "sysconf" , UX_FUNC },
    { "syslog"  , UX_FUNC },
    { "system"  , UX_FUNC | UX_C89 | UX_C99 },
    { "tan" , UX_FUNC | UX_C89 | UX_C99 },
    { "tanf"  , UX_FUNC | UX_C99 },
    { "tanh"  , UX_FUNC | UX_C89 | UX_C99 },
    { "tanhf" , UX_FUNC | UX_C99 },
    { "tanhl" , UX_FUNC | UX_C99 },
    { "tanl"  , UX_FUNC | UX_C99 },
    { "tcdrain" , UX_FUNC },
    { "tcflow"  , UX_FUNC },
    { "tcflush" , UX_FUNC },
    { "tcgetattr" , UX_FUNC },
    { "tcgetpgrp" , UX_FUNC },
    { "tcgetsid"  , UX_FUNC },
    { "tcsendbreak" , UX_FUNC },
    { "tcsetattr" , UX_FUNC },
    { "tcsetpgrp" , UX_FUNC },
    { "tdelete" , UX_FUNC },
    { "telldir" , UX_FUNC },
    { "tempnam" , UX_FUNC },
    { "tfind" , UX_FUNC },
    { "tgamma"  , UX_FUNC | UX_C99 },
    { "tgammaf" , UX_FUNC | UX_C99 },
    { "tgammal" , UX_FUNC | UX_C99 },
    { "time"  , UX_FUNC | UX_C89 | UX_C99 },
    { "timer_create"  , UX_FUNC },
    { "timer_delete"  , UX_FUNC },
    { "timer_getoverrun"  , UX_FUNC },
    { "timer_gettime" , UX_FUNC },
    { "timer_settime" , UX_FUNC },
    { "times" , UX_FUNC },
    { "timezone"  , 0 },
    { "tmpfile" , UX_FUNC | UX_C89 | UX_C99 },
    { "tmpnam"  , UX_FUNC | UX_C89 | UX_C99 },
    { "toascii" , UX_FUNC },
    { "tolower" , UX_FUNC | UX_C89 | UX_C99 },
    { "toupper" , UX_FUNC | UX_C89 | UX_C99 },
    { "towctrans" , UX_FUNC | UX_C99 },
    { "towlower"  , UX_FUNC | UX_C99 },
    { "towupper"  , UX_FUNC | UX_C99 },
    { "trunc" , UX_FUNC | UX_C99 },
    { "truncate"  , UX_FUNC },
    { "truncf"  , UX_FUNC | UX_C99 },
    { "truncl"  , UX_FUNC | UX_C99 },
    { "tsearch" , UX_FUNC },
    { "ttyname" , UX_FUNC },
    { "ttyname_r" , UX_FUNC },
    { "twalk" , UX_FUNC },
    { "tzname"  , 0 },
    { "tzset" , UX_FUNC },
    { "ualarm"  , UX_FUNC },
    { "ulimit"  , UX_FUNC },
    { "umask" , UX_FUNC },
    { "uname" , UX_FUNC },
    { "ungetc"  , UX_FUNC | UX_C89 | UX_C99 },
    { "ungetwc" , UX_FUNC | UX_C99 },
    { "unlink"  , UX_FUNC },
    { "unlockpt"  , UX_FUNC },
    { "unsetenv"  , UX_FUNC },
    { "usleep"  , UX_FUNC },
    { "utime" , UX_FUNC },
    { "utimes"  , UX_FUNC },
    { "va_arg"  , UX_FUNC },
    { "va_copy" , UX_FUNC },
    { "va_end"  , UX_FUNC },
    { "va_start"  , UX_FUNC },
    { "vfork" , UX_FUNC },
    { "vfprintf"  , UX_FUNC },
    { "vfscanf" , UX_FUNC | UX_C99 },
    { "vfwprintf" , UX_FUNC | UX_C99 },
    { "vfwscanf"  , UX_FUNC | UX_C99 },
    { "vprintf" , UX_FUNC | UX_C89 | UX_C99 },
    { "vscanf"  , UX_FUNC | UX_C99 },
    { "vsnprintf" , UX_FUNC | UX_C99 },
    { "vsprintf"  , UX_FUNC | UX_C89 | UX_C99 },
    { "vsscanf" , UX_FUNC | UX_C99 },
    { "vswprintf" , UX_FUNC | UX_C99 },
    { "vswscanf"  , UX_FUNC | UX_C99 },
    { "vwprintf"  , UX_FUNC | UX_C99 },
    { "vwscanf" , UX_FUNC | UX_C99 },
    { "wait"  , UX_FUNC },
    { "waitid"  , UX_FUNC },
    { "waitpid" , UX_FUNC },
    { "wcrtomb" , UX_FUNC | UX_C99 },
    { "wcscat"  , UX_FUNC | UX_C99 },
    { "wcschr"  , UX_FUNC | UX_C99 },
    { "wcscmp"  , UX_FUNC | UX_C99 },
    { "wcscoll" , UX_FUNC | UX_C99 },
    { "wcscpy"  , UX_FUNC | UX_C99 },
    { "wcscspn" , UX_FUNC | UX_C99 },
    { "wcsftime"  , UX_FUNC | UX_C99 },
    { "wcslen"  , UX_FUNC | UX_C99 },
    { "wcsncat" , UX_FUNC | UX_C99 },
    { "wcsncmp" , UX_FUNC | UX_C99 },
    { "wcsncpy" , UX_FUNC | UX_C99 },
    { "wcspbrk" , UX_FUNC | UX_C99 },
    { "wcsrchr" , UX_FUNC | UX_C99 },
    { "wcsrtombs" , UX_FUNC | UX_C99 },
    { "wcsspn"  , UX_FUNC | UX_C99 },
    { "wcsstr"  , UX_FUNC | UX_C99 },
    { "wcstod"  , UX_FUNC | UX_C99 },
    { "wcstof"  , UX_FUNC | UX_C99 },
    { "wcstoimax" , UX_FUNC | UX_C99 },
    { "wcstok"  , UX_FUNC | UX_C99 },
    { "wcstol"  , UX_FUNC | UX_C99 },
    { "wcstold" , UX_FUNC | UX_C99 },
    { "wcstoll" , UX_FUNC | UX_C99 },
    { "wcstombs"  , UX_FUNC | UX_C89 | UX_C99 },
    { "wcstoul" , UX_FUNC | UX_C99 },
    { "wcstoull"  , UX_FUNC | UX_C99 },
    { "wcstoumax" , UX_FUNC | UX_C99 },
    { "wcswcs"  , UX_FUNC },
    { "wcswidth"  , UX_FUNC },
    { "wcsxfrm" , UX_FUNC | UX_C99 },
    { "wctob" , UX_FUNC | UX_C99 },
    { "wctomb"  , UX_FUNC | UX_C89 | UX_C99 },
    { "wctrans" , UX_FUNC | UX_C99 },
    { "wctype"  , UX_FUNC | UX_C99 },
    { "wcwidth" , UX_FUNC },
    { "wmemchr" , UX_FUNC | UX_C99 },
    { "wmemcmp" , UX_FUNC | UX_C99 },
    { "wmemcpy" , UX_FUNC | UX_C99 },
    { "wmemmove"  , UX_FUNC | UX_C99 },
    { "wmemset" , UX_FUNC | UX_C99 },
    { "wordexp" , UX_FUNC },
    { "wordfree"  , UX_FUNC },
    { "wprintf" , UX_FUNC | UX_C99 },
    { "write" , UX_FUNC },
    { "writev"  , UX_FUNC },
    { "wscanf"  , UX_FUNC | UX_C99 },
    { "y0"  , UX_FUNC },
    { "y1"  , UX_FUNC },
    { "yn"  , UX_FUNC },

};


int main ()
{
  int i = 0;
  int mask = UX_C89;
  char tmp [1024];

  // void* axlibc = dlopen ("./lib/i686/debug/libaxc.so", RTLD_LAZY);

  for (i = 0; i < 1123; ++i) {

    if (axHeaderTable[i]._flags & mask) {

      strcpy (tmp, "nm ./lib/i686/debug/libaxc.so | grep ");
      strcat (tmp, axHeaderTable[i]._name);
      strcat (tmp, " > /dev/null");

      // void* sd = dlsym (axlibc, axHeaderTable[i]._name);
      int val = system (tmp);
      if (val) {
        printf (" - %s\n", axHeaderTable[i]._name);
      } else {
        printf (" - <s>%s</s>\n", axHeaderTable[i]._name);
      }
    }

    // printf ("%5d\t%s\n", axHeaderTable[i]._flags, axHeaderTable[i]._name);
  }

  return 0;
}





